import LeanCert
import Riemann.ZetaSurface.CliffordRH
import Mathlib.NumberTheory.SmoothNumbers
import Mathlib.Analysis.SpecialFunctions.Pow.Real

/-!
# Rotor Trace Computation — Certified Bound

Proves `CliffordRH.rotorTrace (1/2) 14.134725 (Nat.primesBelow 7920).toList < -5`
using LeanCert interval arithmetic, eliminating `rotorTrace_first1000_lt_bound_axiom`.

Architecture:
- Manual range reduction: cos(t·log p) = (-1)^k · cos(t·log p - k·π)
  using LeanCert's Expr.pi (16-digit precision) instead of the built-in
  cosComputableReduced (6-digit π bounds)
- Per-term evaluation: each term evaluated independently via evalIntervalCore1,
  rational upper bound extracted and accumulated via exact ℚ arithmetic
- ONE `native_decide` call verifies the accumulated bound

Generated by gen_rotor_trace.py (trace ≈ -5.9543)
-/

set_option maxRecDepth 8192

open LeanCert.Core LeanCert.Validity LeanCert.Engine

namespace RotorTraceComputation

/-! ## Part 1: Prime List -/

/-- The 1000 primes below 7920, as a concrete list. -/
def primeList : List ℕ := [
  2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71,
  73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173,
  179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281,
  283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409,
  419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541,
  547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659,
  661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809,
  811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941,
  947, 953, 967, 971, 977, 983, 991, 997, 1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069,
  1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 1151, 1153, 1163, 1171, 1181, 1187, 1193, 1201, 1213, 1217, 1223,
  1229, 1231, 1237, 1249, 1259, 1277, 1279, 1283, 1289, 1291, 1297, 1301, 1303, 1307, 1319, 1321, 1327, 1361, 1367, 1373,
  1381, 1399, 1409, 1423, 1427, 1429, 1433, 1439, 1447, 1451, 1453, 1459, 1471, 1481, 1483, 1487, 1489, 1493, 1499, 1511,
  1523, 1531, 1543, 1549, 1553, 1559, 1567, 1571, 1579, 1583, 1597, 1601, 1607, 1609, 1613, 1619, 1621, 1627, 1637, 1657,
  1663, 1667, 1669, 1693, 1697, 1699, 1709, 1721, 1723, 1733, 1741, 1747, 1753, 1759, 1777, 1783, 1787, 1789, 1801, 1811,
  1823, 1831, 1847, 1861, 1867, 1871, 1873, 1877, 1879, 1889, 1901, 1907, 1913, 1931, 1933, 1949, 1951, 1973, 1979, 1987,
  1993, 1997, 1999, 2003, 2011, 2017, 2027, 2029, 2039, 2053, 2063, 2069, 2081, 2083, 2087, 2089, 2099, 2111, 2113, 2129,
  2131, 2137, 2141, 2143, 2153, 2161, 2179, 2203, 2207, 2213, 2221, 2237, 2239, 2243, 2251, 2267, 2269, 2273, 2281, 2287,
  2293, 2297, 2309, 2311, 2333, 2339, 2341, 2347, 2351, 2357, 2371, 2377, 2381, 2383, 2389, 2393, 2399, 2411, 2417, 2423,
  2437, 2441, 2447, 2459, 2467, 2473, 2477, 2503, 2521, 2531, 2539, 2543, 2549, 2551, 2557, 2579, 2591, 2593, 2609, 2617,
  2621, 2633, 2647, 2657, 2659, 2663, 2671, 2677, 2683, 2687, 2689, 2693, 2699, 2707, 2711, 2713, 2719, 2729, 2731, 2741,
  2749, 2753, 2767, 2777, 2789, 2791, 2797, 2801, 2803, 2819, 2833, 2837, 2843, 2851, 2857, 2861, 2879, 2887, 2897, 2903,
  2909, 2917, 2927, 2939, 2953, 2957, 2963, 2969, 2971, 2999, 3001, 3011, 3019, 3023, 3037, 3041, 3049, 3061, 3067, 3079,
  3083, 3089, 3109, 3119, 3121, 3137, 3163, 3167, 3169, 3181, 3187, 3191, 3203, 3209, 3217, 3221, 3229, 3251, 3253, 3257,
  3259, 3271, 3299, 3301, 3307, 3313, 3319, 3323, 3329, 3331, 3343, 3347, 3359, 3361, 3371, 3373, 3389, 3391, 3407, 3413,
  3433, 3449, 3457, 3461, 3463, 3467, 3469, 3491, 3499, 3511, 3517, 3527, 3529, 3533, 3539, 3541, 3547, 3557, 3559, 3571,
  3581, 3583, 3593, 3607, 3613, 3617, 3623, 3631, 3637, 3643, 3659, 3671, 3673, 3677, 3691, 3697, 3701, 3709, 3719, 3727,
  3733, 3739, 3761, 3767, 3769, 3779, 3793, 3797, 3803, 3821, 3823, 3833, 3847, 3851, 3853, 3863, 3877, 3881, 3889, 3907,
  3911, 3917, 3919, 3923, 3929, 3931, 3943, 3947, 3967, 3989, 4001, 4003, 4007, 4013, 4019, 4021, 4027, 4049, 4051, 4057,
  4073, 4079, 4091, 4093, 4099, 4111, 4127, 4129, 4133, 4139, 4153, 4157, 4159, 4177, 4201, 4211, 4217, 4219, 4229, 4231,
  4241, 4243, 4253, 4259, 4261, 4271, 4273, 4283, 4289, 4297, 4327, 4337, 4339, 4349, 4357, 4363, 4373, 4391, 4397, 4409,
  4421, 4423, 4441, 4447, 4451, 4457, 4463, 4481, 4483, 4493, 4507, 4513, 4517, 4519, 4523, 4547, 4549, 4561, 4567, 4583,
  4591, 4597, 4603, 4621, 4637, 4639, 4643, 4649, 4651, 4657, 4663, 4673, 4679, 4691, 4703, 4721, 4723, 4729, 4733, 4751,
  4759, 4783, 4787, 4789, 4793, 4799, 4801, 4813, 4817, 4831, 4861, 4871, 4877, 4889, 4903, 4909, 4919, 4931, 4933, 4937,
  4943, 4951, 4957, 4967, 4969, 4973, 4987, 4993, 4999, 5003, 5009, 5011, 5021, 5023, 5039, 5051, 5059, 5077, 5081, 5087,
  5099, 5101, 5107, 5113, 5119, 5147, 5153, 5167, 5171, 5179, 5189, 5197, 5209, 5227, 5231, 5233, 5237, 5261, 5273, 5279,
  5281, 5297, 5303, 5309, 5323, 5333, 5347, 5351, 5381, 5387, 5393, 5399, 5407, 5413, 5417, 5419, 5431, 5437, 5441, 5443,
  5449, 5471, 5477, 5479, 5483, 5501, 5503, 5507, 5519, 5521, 5527, 5531, 5557, 5563, 5569, 5573, 5581, 5591, 5623, 5639,
  5641, 5647, 5651, 5653, 5657, 5659, 5669, 5683, 5689, 5693, 5701, 5711, 5717, 5737, 5741, 5743, 5749, 5779, 5783, 5791,
  5801, 5807, 5813, 5821, 5827, 5839, 5843, 5849, 5851, 5857, 5861, 5867, 5869, 5879, 5881, 5897, 5903, 5923, 5927, 5939,
  5953, 5981, 5987, 6007, 6011, 6029, 6037, 6043, 6047, 6053, 6067, 6073, 6079, 6089, 6091, 6101, 6113, 6121, 6131, 6133,
  6143, 6151, 6163, 6173, 6197, 6199, 6203, 6211, 6217, 6221, 6229, 6247, 6257, 6263, 6269, 6271, 6277, 6287, 6299, 6301,
  6311, 6317, 6323, 6329, 6337, 6343, 6353, 6359, 6361, 6367, 6373, 6379, 6389, 6397, 6421, 6427, 6449, 6451, 6469, 6473,
  6481, 6491, 6521, 6529, 6547, 6551, 6553, 6563, 6569, 6571, 6577, 6581, 6599, 6607, 6619, 6637, 6653, 6659, 6661, 6673,
  6679, 6689, 6691, 6701, 6703, 6709, 6719, 6733, 6737, 6761, 6763, 6779, 6781, 6791, 6793, 6803, 6823, 6827, 6829, 6833,
  6841, 6857, 6863, 6869, 6871, 6883, 6899, 6907, 6911, 6917, 6947, 6949, 6959, 6961, 6967, 6971, 6977, 6983, 6991, 6997,
  7001, 7013, 7019, 7027, 7039, 7043, 7057, 7069, 7079, 7103, 7109, 7121, 7127, 7129, 7151, 7159, 7177, 7187, 7193, 7207,
  7211, 7213, 7219, 7229, 7237, 7243, 7247, 7253, 7283, 7297, 7307, 7309, 7321, 7331, 7333, 7349, 7351, 7369, 7393, 7411,
  7417, 7433, 7451, 7457, 7459, 7477, 7481, 7487, 7489, 7499, 7507, 7517, 7523, 7529, 7537, 7541, 7547, 7549, 7559, 7561,
  7573, 7577, 7583, 7589, 7591, 7603, 7607, 7621, 7639, 7643, 7649, 7669, 7673, 7681, 7687, 7691, 7699, 7703, 7717, 7723,
  7727, 7741, 7753, 7757, 7759, 7789, 7793, 7817, 7823, 7829, 7841, 7853, 7867, 7873, 7877, 7879, 7883, 7901, 7907, 7919
]

/-! ## Part 2: LeanCert Expression with Manual Range Reduction -/

/-- One term of the rotorTrace sum as a LeanCert Expr with manual range reduction.
    cos(t·log p) = (-1)^k · cos(t·log p - k·π) where reduced arg ∈ [0, π].
    This avoids the built-in cosComputableReduced which uses crude π bounds. -/
def mkRotorTermReduced (p : ℚ) (k : ℤ) (negSign : Bool) : Expr :=
  let cosArg := .add (.mul (.const (565389/40000)) (.log (.const p)))
                     (.neg (.mul (.const k) .pi))
  let cosTerm := .cos cosArg
  let signedCos := if negSign then .neg cosTerm else cosTerm
  .mul (.mul (.log (.const p))
             (.exp (.neg (.mul (.log (.const p)) (.const (1/2))))))
       signedCos

/-- Per-term interval evaluation using evalIntervalCore1. -/
def termIntervalReduced (p : ℕ) (k : ℤ) (negSign : Bool) (cfg : EvalConfig) : IntervalRat :=
  evalIntervalCore1 (mkRotorTermReduced p k negSign) ⟨0, 0, le_refl _⟩ cfg

/-- The term data: (prime, k, negSign) for manual range reduction. -/
def allTerms : List (ℕ × ℤ × Bool) := [
  (2, 3, true), (3, 4, false), (5, 7, true), (7, 8, false), (11, 10, false),
  (13, 11, true), (17, 12, false), (19, 13, true), (23, 14, false), (29, 15, true),
  (31, 15, true), (37, 16, false), (41, 16, false), (43, 16, false), (47, 17, true),
  (53, 17, true), (59, 18, false), (61, 18, false), (67, 18, false), (71, 19, true),
  (73, 19, true), (79, 19, true), (83, 19, true), (89, 20, false), (97, 20, false),
  (101, 20, false), (103, 20, false), (107, 21, true), (109, 21, true), (113, 21, true),
  (127, 21, true), (131, 21, true), (137, 22, false), (139, 22, false), (149, 22, false),
  (151, 22, false), (157, 22, false), (163, 22, false), (167, 23, true), (173, 23, true),
  (179, 23, true), (181, 23, true), (191, 23, true), (193, 23, true), (197, 23, true),
  (199, 23, true), (211, 24, false), (223, 24, false), (227, 24, false), (229, 24, false),
  (233, 24, false), (239, 24, false), (241, 24, false), (251, 24, false), (257, 24, false),
  (263, 25, true), (269, 25, true), (271, 25, true), (277, 25, true), (281, 25, true),
  (283, 25, true), (293, 25, true), (307, 25, true), (311, 25, true), (313, 25, true),
  (317, 25, true), (331, 26, false), (337, 26, false), (347, 26, false), (349, 26, false),
  (353, 26, false), (359, 26, false), (367, 26, false), (373, 26, false), (379, 26, false),
  (383, 26, false), (389, 26, false), (397, 26, false), (401, 26, false), (409, 27, true),
  (419, 27, true), (421, 27, true), (431, 27, true), (433, 27, true), (439, 27, true),
  (443, 27, true), (449, 27, true), (457, 27, true), (461, 27, true), (463, 27, true),
  (467, 27, true), (479, 27, true), (487, 27, true), (491, 27, true), (499, 27, true),
  (503, 27, true), (509, 28, false), (521, 28, false), (523, 28, false), (541, 28, false),
  (547, 28, false), (557, 28, false), (563, 28, false), (569, 28, false), (571, 28, false),
  (577, 28, false), (587, 28, false), (593, 28, false), (599, 28, false), (601, 28, false),
  (607, 28, false), (613, 28, false), (617, 28, false), (619, 28, false), (631, 29, true),
  (641, 29, true), (643, 29, true), (647, 29, true), (653, 29, true), (659, 29, true),
  (661, 29, true), (673, 29, true), (677, 29, true), (683, 29, true), (691, 29, true),
  (701, 29, true), (709, 29, true), (719, 29, true), (727, 29, true), (733, 29, true),
  (739, 29, true), (743, 29, true), (751, 29, true), (757, 29, true), (761, 29, true),
  (769, 29, true), (773, 29, true), (787, 30, false), (797, 30, false), (809, 30, false),
  (811, 30, false), (821, 30, false), (823, 30, false), (827, 30, false), (829, 30, false),
  (839, 30, false), (853, 30, false), (857, 30, false), (859, 30, false), (863, 30, false),
  (877, 30, false), (881, 30, false), (883, 30, false), (887, 30, false), (907, 30, false),
  (911, 30, false), (919, 30, false), (929, 30, false), (937, 30, false), (941, 30, false),
  (947, 30, false), (953, 30, false), (967, 30, false), (971, 30, false), (977, 30, false),
  (983, 31, true), (991, 31, true), (997, 31, true), (1009, 31, true), (1013, 31, true),
  (1019, 31, true), (1021, 31, true), (1031, 31, true), (1033, 31, true), (1039, 31, true),
  (1049, 31, true), (1051, 31, true), (1061, 31, true), (1063, 31, true), (1069, 31, true),
  (1087, 31, true), (1091, 31, true), (1093, 31, true), (1097, 31, true), (1103, 31, true),
  (1109, 31, true), (1117, 31, true), (1123, 31, true), (1129, 31, true), (1151, 31, true),
  (1153, 31, true), (1163, 31, true), (1171, 31, true), (1181, 31, true), (1187, 31, true),
  (1193, 31, true), (1201, 31, true), (1213, 31, true), (1217, 31, true), (1223, 31, true),
  (1229, 32, false), (1231, 32, false), (1237, 32, false), (1249, 32, false), (1259, 32, false),
  (1277, 32, false), (1279, 32, false), (1283, 32, false), (1289, 32, false), (1291, 32, false),
  (1297, 32, false), (1301, 32, false), (1303, 32, false), (1307, 32, false), (1319, 32, false),
  (1321, 32, false), (1327, 32, false), (1361, 32, false), (1367, 32, false), (1373, 32, false),
  (1381, 32, false), (1399, 32, false), (1409, 32, false), (1423, 32, false), (1427, 32, false),
  (1429, 32, false), (1433, 32, false), (1439, 32, false), (1447, 32, false), (1451, 32, false),
  (1453, 32, false), (1459, 32, false), (1471, 32, false), (1481, 32, false), (1483, 32, false),
  (1487, 32, false), (1489, 32, false), (1493, 32, false), (1499, 32, false), (1511, 32, false),
  (1523, 32, false), (1531, 32, false), (1543, 33, true), (1549, 33, true), (1553, 33, true),
  (1559, 33, true), (1567, 33, true), (1571, 33, true), (1579, 33, true), (1583, 33, true),
  (1597, 33, true), (1601, 33, true), (1607, 33, true), (1609, 33, true), (1613, 33, true),
  (1619, 33, true), (1621, 33, true), (1627, 33, true), (1637, 33, true), (1657, 33, true),
  (1663, 33, true), (1667, 33, true), (1669, 33, true), (1693, 33, true), (1697, 33, true),
  (1699, 33, true), (1709, 33, true), (1721, 33, true), (1723, 33, true), (1733, 33, true),
  (1741, 33, true), (1747, 33, true), (1753, 33, true), (1759, 33, true), (1777, 33, true),
  (1783, 33, true), (1787, 33, true), (1789, 33, true), (1801, 33, true), (1811, 33, true),
  (1823, 33, true), (1831, 33, true), (1847, 33, true), (1861, 33, true), (1867, 33, true),
  (1871, 33, true), (1873, 33, true), (1877, 33, true), (1879, 33, true), (1889, 33, true),
  (1901, 33, true), (1907, 33, true), (1913, 33, true), (1931, 34, false), (1933, 34, false),
  (1949, 34, false), (1951, 34, false), (1973, 34, false), (1979, 34, false), (1987, 34, false),
  (1993, 34, false), (1997, 34, false), (1999, 34, false), (2003, 34, false), (2011, 34, false),
  (2017, 34, false), (2027, 34, false), (2029, 34, false), (2039, 34, false), (2053, 34, false),
  (2063, 34, false), (2069, 34, false), (2081, 34, false), (2083, 34, false), (2087, 34, false),
  (2089, 34, false), (2099, 34, false), (2111, 34, false), (2113, 34, false), (2129, 34, false),
  (2131, 34, false), (2137, 34, false), (2141, 34, false), (2143, 34, false), (2153, 34, false),
  (2161, 34, false), (2179, 34, false), (2203, 34, false), (2207, 34, false), (2213, 34, false),
  (2221, 34, false), (2237, 34, false), (2239, 34, false), (2243, 34, false), (2251, 34, false),
  (2267, 34, false), (2269, 34, false), (2273, 34, false), (2281, 34, false), (2287, 34, false),
  (2293, 34, false), (2297, 34, false), (2309, 34, false), (2311, 34, false), (2333, 34, false),
  (2339, 34, false), (2341, 34, false), (2347, 34, false), (2351, 34, false), (2357, 34, false),
  (2371, 34, false), (2377, 34, false), (2381, 34, false), (2383, 34, false), (2389, 34, false),
  (2393, 35, true), (2399, 35, true), (2411, 35, true), (2417, 35, true), (2423, 35, true),
  (2437, 35, true), (2441, 35, true), (2447, 35, true), (2459, 35, true), (2467, 35, true),
  (2473, 35, true), (2477, 35, true), (2503, 35, true), (2521, 35, true), (2531, 35, true),
  (2539, 35, true), (2543, 35, true), (2549, 35, true), (2551, 35, true), (2557, 35, true),
  (2579, 35, true), (2591, 35, true), (2593, 35, true), (2609, 35, true), (2617, 35, true),
  (2621, 35, true), (2633, 35, true), (2647, 35, true), (2657, 35, true), (2659, 35, true),
  (2663, 35, true), (2671, 35, true), (2677, 35, true), (2683, 35, true), (2687, 35, true),
  (2689, 35, true), (2693, 35, true), (2699, 35, true), (2707, 35, true), (2711, 35, true),
  (2713, 35, true), (2719, 35, true), (2729, 35, true), (2731, 35, true), (2741, 35, true),
  (2749, 35, true), (2753, 35, true), (2767, 35, true), (2777, 35, true), (2789, 35, true),
  (2791, 35, true), (2797, 35, true), (2801, 35, true), (2803, 35, true), (2819, 35, true),
  (2833, 35, true), (2837, 35, true), (2843, 35, true), (2851, 35, true), (2857, 35, true),
  (2861, 35, true), (2879, 35, true), (2887, 35, true), (2897, 35, true), (2903, 35, true),
  (2909, 35, true), (2917, 35, true), (2927, 35, true), (2939, 35, true), (2953, 35, true),
  (2957, 35, true), (2963, 35, true), (2969, 35, true), (2971, 35, true), (2999, 36, false),
  (3001, 36, false), (3011, 36, false), (3019, 36, false), (3023, 36, false), (3037, 36, false),
  (3041, 36, false), (3049, 36, false), (3061, 36, false), (3067, 36, false), (3079, 36, false),
  (3083, 36, false), (3089, 36, false), (3109, 36, false), (3119, 36, false), (3121, 36, false),
  (3137, 36, false), (3163, 36, false), (3167, 36, false), (3169, 36, false), (3181, 36, false),
  (3187, 36, false), (3191, 36, false), (3203, 36, false), (3209, 36, false), (3217, 36, false),
  (3221, 36, false), (3229, 36, false), (3251, 36, false), (3253, 36, false), (3257, 36, false),
  (3259, 36, false), (3271, 36, false), (3299, 36, false), (3301, 36, false), (3307, 36, false),
  (3313, 36, false), (3319, 36, false), (3323, 36, false), (3329, 36, false), (3331, 36, false),
  (3343, 36, false), (3347, 36, false), (3359, 36, false), (3361, 36, false), (3371, 36, false),
  (3373, 36, false), (3389, 36, false), (3391, 36, false), (3407, 36, false), (3413, 36, false),
  (3433, 36, false), (3449, 36, false), (3457, 36, false), (3461, 36, false), (3463, 36, false),
  (3467, 36, false), (3469, 36, false), (3491, 36, false), (3499, 36, false), (3511, 36, false),
  (3517, 36, false), (3527, 36, false), (3529, 36, false), (3533, 36, false), (3539, 36, false),
  (3541, 36, false), (3547, 36, false), (3557, 36, false), (3559, 36, false), (3571, 36, false),
  (3581, 36, false), (3583, 36, false), (3593, 36, false), (3607, 36, false), (3613, 36, false),
  (3617, 36, false), (3623, 36, false), (3631, 36, false), (3637, 36, false), (3643, 36, false),
  (3659, 36, false), (3671, 36, false), (3673, 36, false), (3677, 36, false), (3691, 36, false),
  (3697, 36, false), (3701, 36, false), (3709, 36, false), (3719, 36, false), (3727, 36, false),
  (3733, 37, true), (3739, 37, true), (3761, 37, true), (3767, 37, true), (3769, 37, true),
  (3779, 37, true), (3793, 37, true), (3797, 37, true), (3803, 37, true), (3821, 37, true),
  (3823, 37, true), (3833, 37, true), (3847, 37, true), (3851, 37, true), (3853, 37, true),
  (3863, 37, true), (3877, 37, true), (3881, 37, true), (3889, 37, true), (3907, 37, true),
  (3911, 37, true), (3917, 37, true), (3919, 37, true), (3923, 37, true), (3929, 37, true),
  (3931, 37, true), (3943, 37, true), (3947, 37, true), (3967, 37, true), (3989, 37, true),
  (4001, 37, true), (4003, 37, true), (4007, 37, true), (4013, 37, true), (4019, 37, true),
  (4021, 37, true), (4027, 37, true), (4049, 37, true), (4051, 37, true), (4057, 37, true),
  (4073, 37, true), (4079, 37, true), (4091, 37, true), (4093, 37, true), (4099, 37, true),
  (4111, 37, true), (4127, 37, true), (4129, 37, true), (4133, 37, true), (4139, 37, true),
  (4153, 37, true), (4157, 37, true), (4159, 37, true), (4177, 37, true), (4201, 37, true),
  (4211, 37, true), (4217, 37, true), (4219, 37, true), (4229, 37, true), (4231, 37, true),
  (4241, 37, true), (4243, 37, true), (4253, 37, true), (4259, 37, true), (4261, 37, true),
  (4271, 37, true), (4273, 37, true), (4283, 37, true), (4289, 37, true), (4297, 37, true),
  (4327, 37, true), (4337, 37, true), (4339, 37, true), (4349, 37, true), (4357, 37, true),
  (4363, 37, true), (4373, 37, true), (4391, 37, true), (4397, 37, true), (4409, 37, true),
  (4421, 37, true), (4423, 37, true), (4441, 37, true), (4447, 37, true), (4451, 37, true),
  (4457, 37, true), (4463, 37, true), (4481, 37, true), (4483, 37, true), (4493, 37, true),
  (4507, 37, true), (4513, 37, true), (4517, 37, true), (4519, 37, true), (4523, 37, true),
  (4547, 37, true), (4549, 37, true), (4561, 37, true), (4567, 37, true), (4583, 37, true),
  (4591, 37, true), (4597, 37, true), (4603, 37, true), (4621, 37, true), (4637, 37, true),
  (4639, 37, true), (4643, 37, true), (4649, 37, true), (4651, 37, true), (4657, 38, false),
  (4663, 38, false), (4673, 38, false), (4679, 38, false), (4691, 38, false), (4703, 38, false),
  (4721, 38, false), (4723, 38, false), (4729, 38, false), (4733, 38, false), (4751, 38, false),
  (4759, 38, false), (4783, 38, false), (4787, 38, false), (4789, 38, false), (4793, 38, false),
  (4799, 38, false), (4801, 38, false), (4813, 38, false), (4817, 38, false), (4831, 38, false),
  (4861, 38, false), (4871, 38, false), (4877, 38, false), (4889, 38, false), (4903, 38, false),
  (4909, 38, false), (4919, 38, false), (4931, 38, false), (4933, 38, false), (4937, 38, false),
  (4943, 38, false), (4951, 38, false), (4957, 38, false), (4967, 38, false), (4969, 38, false),
  (4973, 38, false), (4987, 38, false), (4993, 38, false), (4999, 38, false), (5003, 38, false),
  (5009, 38, false), (5011, 38, false), (5021, 38, false), (5023, 38, false), (5039, 38, false),
  (5051, 38, false), (5059, 38, false), (5077, 38, false), (5081, 38, false), (5087, 38, false),
  (5099, 38, false), (5101, 38, false), (5107, 38, false), (5113, 38, false), (5119, 38, false),
  (5147, 38, false), (5153, 38, false), (5167, 38, false), (5171, 38, false), (5179, 38, false),
  (5189, 38, false), (5197, 38, false), (5209, 38, false), (5227, 38, false), (5231, 38, false),
  (5233, 38, false), (5237, 38, false), (5261, 38, false), (5273, 38, false), (5279, 38, false),
  (5281, 38, false), (5297, 38, false), (5303, 38, false), (5309, 38, false), (5323, 38, false),
  (5333, 38, false), (5347, 38, false), (5351, 38, false), (5381, 38, false), (5387, 38, false),
  (5393, 38, false), (5399, 38, false), (5407, 38, false), (5413, 38, false), (5417, 38, false),
  (5419, 38, false), (5431, 38, false), (5437, 38, false), (5441, 38, false), (5443, 38, false),
  (5449, 38, false), (5471, 38, false), (5477, 38, false), (5479, 38, false), (5483, 38, false),
  (5501, 38, false), (5503, 38, false), (5507, 38, false), (5519, 38, false), (5521, 38, false),
  (5527, 38, false), (5531, 38, false), (5557, 38, false), (5563, 38, false), (5569, 38, false),
  (5573, 38, false), (5581, 38, false), (5591, 38, false), (5623, 38, false), (5639, 38, false),
  (5641, 38, false), (5647, 38, false), (5651, 38, false), (5653, 38, false), (5657, 38, false),
  (5659, 38, false), (5669, 38, false), (5683, 38, false), (5689, 38, false), (5693, 38, false),
  (5701, 38, false), (5711, 38, false), (5717, 38, false), (5737, 38, false), (5741, 38, false),
  (5743, 38, false), (5749, 38, false), (5779, 38, false), (5783, 38, false), (5791, 38, false),
  (5801, 38, false), (5807, 38, false), (5813, 38, false), (5821, 39, true), (5827, 39, true),
  (5839, 39, true), (5843, 39, true), (5849, 39, true), (5851, 39, true), (5857, 39, true),
  (5861, 39, true), (5867, 39, true), (5869, 39, true), (5879, 39, true), (5881, 39, true),
  (5897, 39, true), (5903, 39, true), (5923, 39, true), (5927, 39, true), (5939, 39, true),
  (5953, 39, true), (5981, 39, true), (5987, 39, true), (6007, 39, true), (6011, 39, true),
  (6029, 39, true), (6037, 39, true), (6043, 39, true), (6047, 39, true), (6053, 39, true),
  (6067, 39, true), (6073, 39, true), (6079, 39, true), (6089, 39, true), (6091, 39, true),
  (6101, 39, true), (6113, 39, true), (6121, 39, true), (6131, 39, true), (6133, 39, true),
  (6143, 39, true), (6151, 39, true), (6163, 39, true), (6173, 39, true), (6197, 39, true),
  (6199, 39, true), (6203, 39, true), (6211, 39, true), (6217, 39, true), (6221, 39, true),
  (6229, 39, true), (6247, 39, true), (6257, 39, true), (6263, 39, true), (6269, 39, true),
  (6271, 39, true), (6277, 39, true), (6287, 39, true), (6299, 39, true), (6301, 39, true),
  (6311, 39, true), (6317, 39, true), (6323, 39, true), (6329, 39, true), (6337, 39, true),
  (6343, 39, true), (6353, 39, true), (6359, 39, true), (6361, 39, true), (6367, 39, true),
  (6373, 39, true), (6379, 39, true), (6389, 39, true), (6397, 39, true), (6421, 39, true),
  (6427, 39, true), (6449, 39, true), (6451, 39, true), (6469, 39, true), (6473, 39, true),
  (6481, 39, true), (6491, 39, true), (6521, 39, true), (6529, 39, true), (6547, 39, true),
  (6551, 39, true), (6553, 39, true), (6563, 39, true), (6569, 39, true), (6571, 39, true),
  (6577, 39, true), (6581, 39, true), (6599, 39, true), (6607, 39, true), (6619, 39, true),
  (6637, 39, true), (6653, 39, true), (6659, 39, true), (6661, 39, true), (6673, 39, true),
  (6679, 39, true), (6689, 39, true), (6691, 39, true), (6701, 39, true), (6703, 39, true),
  (6709, 39, true), (6719, 39, true), (6733, 39, true), (6737, 39, true), (6761, 39, true),
  (6763, 39, true), (6779, 39, true), (6781, 39, true), (6791, 39, true), (6793, 39, true),
  (6803, 39, true), (6823, 39, true), (6827, 39, true), (6829, 39, true), (6833, 39, true),
  (6841, 39, true), (6857, 39, true), (6863, 39, true), (6869, 39, true), (6871, 39, true),
  (6883, 39, true), (6899, 39, true), (6907, 39, true), (6911, 39, true), (6917, 39, true),
  (6947, 39, true), (6949, 39, true), (6959, 39, true), (6961, 39, true), (6967, 39, true),
  (6971, 39, true), (6977, 39, true), (6983, 39, true), (6991, 39, true), (6997, 39, true),
  (7001, 39, true), (7013, 39, true), (7019, 39, true), (7027, 39, true), (7039, 39, true),
  (7043, 39, true), (7057, 39, true), (7069, 39, true), (7079, 39, true), (7103, 39, true),
  (7109, 39, true), (7121, 39, true), (7127, 39, true), (7129, 39, true), (7151, 39, true),
  (7159, 39, true), (7177, 39, true), (7187, 39, true), (7193, 39, true), (7207, 39, true),
  (7211, 39, true), (7213, 39, true), (7219, 39, true), (7229, 39, true), (7237, 39, true),
  (7243, 39, true), (7247, 39, true), (7253, 39, true), (7283, 40, false), (7297, 40, false),
  (7307, 40, false), (7309, 40, false), (7321, 40, false), (7331, 40, false), (7333, 40, false),
  (7349, 40, false), (7351, 40, false), (7369, 40, false), (7393, 40, false), (7411, 40, false),
  (7417, 40, false), (7433, 40, false), (7451, 40, false), (7457, 40, false), (7459, 40, false),
  (7477, 40, false), (7481, 40, false), (7487, 40, false), (7489, 40, false), (7499, 40, false),
  (7507, 40, false), (7517, 40, false), (7523, 40, false), (7529, 40, false), (7537, 40, false),
  (7541, 40, false), (7547, 40, false), (7549, 40, false), (7559, 40, false), (7561, 40, false),
  (7573, 40, false), (7577, 40, false), (7583, 40, false), (7589, 40, false), (7591, 40, false),
  (7603, 40, false), (7607, 40, false), (7621, 40, false), (7639, 40, false), (7643, 40, false),
  (7649, 40, false), (7669, 40, false), (7673, 40, false), (7681, 40, false), (7687, 40, false),
  (7691, 40, false), (7699, 40, false), (7703, 40, false), (7717, 40, false), (7723, 40, false),
  (7727, 40, false), (7741, 40, false), (7753, 40, false), (7757, 40, false), (7759, 40, false),
  (7789, 40, false), (7793, 40, false), (7817, 40, false), (7823, 40, false), (7829, 40, false),
  (7841, 40, false), (7853, 40, false), (7867, 40, false), (7873, 40, false), (7877, 40, false),
  (7879, 40, false), (7883, 40, false), (7901, 40, false), (7907, 40, false), (7919, 40, false)
]

/-! ## Part 3: Certified Bound (ONE native_decide call) -/

/-- Cumulative bound checker: evaluate each term individually, sum upper bounds. -/
def rotorTraceCheckReduced
    (terms : List (ℕ × ℤ × Bool)) (bound : ℚ) (cfg : EvalConfig) : Bool :=
  let hiSum := terms.foldl (fun acc (p, k, neg) =>
    acc + (termIntervalReduced p k neg cfg).hi) (0 : ℚ)
  decide (2 * hiSum < bound)

set_option maxHeartbeats 40000000 in
set_option linter.style.nativeDecide false in
/-- The interval arithmetic verification: rotorTrace bound < -5.
    Uses taylorDepth 30 for high-precision transcendental evaluation. -/
theorem fullCheck :
    rotorTraceCheckReduced allTerms (-5) { taylorDepth := 30 } = true := by
  native_decide

/-! ## Part 4: Bridge Lemmas -/

noncomputable section
open Real

/-- ExprSupportedCore proof for mkRotorTermReduced — works for any parameters. -/
theorem mkRotorTermReduced_supported (p : ℚ) (k : ℤ) (neg : Bool) :
    ExprSupportedCore (mkRotorTermReduced p k neg) := by
  unfold mkRotorTermReduced
  cases neg <;> simp only [ite_true, ite_false, Bool.false_eq_true]
  · exact .mul (.mul (.log (.const p))
      (.exp (.neg (.mul (.log (.const p)) (.const (1/2))))))
      (.cos (.add (.mul (.const (565389/40000)) (.log (.const p)))
        (.neg (.mul (.const k) .pi))))
  · exact .mul (.mul (.log (.const p))
      (.exp (.neg (.mul (.log (.const p)) (.const (1/2))))))
      (.neg (.cos (.add (.mul (.const (565389/40000)) (.log (.const p)))
        (.neg (.mul (.const k) .pi)))))

/-- Per-term semantic bound: Expr.eval of mkRotorTermReduced gives an upper bound. -/
theorem termReduced_le_hi (p : ℕ) (k : ℤ) (neg : Bool) (cfg : EvalConfig)
    (hdom : evalDomainValid1 (mkRotorTermReduced p k neg) ⟨0, 0, le_refl _⟩ cfg) :
    Expr.eval (fun _ => (0 : ℝ)) (mkRotorTermReduced p k neg) ≤
    (termIntervalReduced p k neg cfg).hi := by
  have h := evalIntervalCore1_correct (mkRotorTermReduced p k neg)
    (mkRotorTermReduced_supported p k neg)
    0 ⟨0, 0, le_refl _⟩ (by simp [IntervalRat.mem_def]) cfg hdom
  exact h.2

/-! ### Atomic Bridge Lemmas -/

/-- 14.134725 equals 565389/40000 as real numbers. -/
private lemma t_eq : (14.134725 : ℝ) = (565389 : ℝ) / 40000 := by norm_num

/-- exp(-log(p) * (1/2)) = p^(-1/2) for p > 0 (bridges LeanCert Expr to rpow). -/
private lemma exp_neg_half_log (p : ℕ) (hp : 0 < (p : ℝ)) :
    Real.exp (-(Real.log (p : ℝ) * ((1 / 2 : ℚ) : ℝ))) = (p : ℝ) ^ (-(1 : ℝ) / 2) := by
  rw [rpow_def_of_pos hp]; congr 1; push_cast; ring

/-- Signed cosine after range reduction equals the original cosine.
    Uses cos(θ - k*π) = (-1)^k * cos(θ) from Mathlib. -/
private lemma signed_cos_eq (θ : ℝ) (k : ℤ) (neg : Bool) (hneg : neg = decide (k % 2 = 1)) :
    (if neg then -(Real.cos (θ - ↑k * Real.pi)) else Real.cos (θ - ↑k * Real.pi)) =
    Real.cos θ := by
  subst hneg
  rcases Int.even_or_odd k with ⟨m, hm⟩ | ⟨m, hm⟩
  · -- k = m + m (even)
    have hmod : k % 2 = 0 := by omega
    have hd : ¬(decide (k % 2 = 1) = true) := by rw [hmod]; decide
    rw [if_neg hd, hm, show (↑(m + m) : ℝ) * π = ↑m * (2 * π) from by push_cast; ring]
    exact cos_sub_int_mul_two_pi θ m
  · -- k = 2*m + 1 (odd)
    have hmod : k % 2 = 1 := by omega
    have hd : decide (k % 2 = 1) = true := by rw [hmod]; decide
    rw [if_pos hd, hm, show (↑(2 * m + 1) : ℝ) * π = ↑m * (2 * π) + π from by push_cast; ring,
        show θ - (↑m * (2 * π) + π) = (θ - π) - ↑m * (2 * π) from by ring]
    rw [cos_sub_int_mul_two_pi (θ - π) m]
    rw [show θ - π = θ + (-1 : ℤ) * π from by push_cast; ring]
    rw [cos_add_int_mul_pi θ (-1)]
    simp

/-- Per-term bridge: Expr.eval of mkRotorTermReduced equals the actual rotorTrace term.
    Combines exp-to-rpow conversion and cosine range reduction. -/
private lemma mkTermReduced_eval_eq (p : ℕ) (hp : 0 < (p : ℝ)) (k : ℤ) (neg : Bool)
    (hneg : neg = decide (k % 2 = 1)) :
    Expr.eval (fun _ => (0 : ℝ)) (mkRotorTermReduced p k neg) =
    Real.log (p : ℝ) * (p : ℝ) ^ (-(1 : ℝ) / 2) *
    Real.cos ((565389 : ℝ) / 40000 * Real.log (p : ℝ)) := by
  subst hneg
  unfold mkRotorTermReduced
  simp only [apply_ite (Expr.eval _), Expr.eval_mul, Expr.eval_log, Expr.eval_const,
    Expr.eval_exp, Expr.eval_neg, Expr.eval_cos, Expr.eval_add, Expr.eval_pi,
    Rat.cast_natCast, Rat.cast_intCast]
  rw [exp_neg_half_log p hp]
  congr 1
  -- Goal: (if decide(k%2=1)=true then -cos(X) else cos(X)) = cos(Y)
  -- X has + -(↑k * π), but signed_cos_eq uses - ↑k * π (sub vs add neg)
  have hscos := signed_cos_eq (((565389 / 40000 : ℚ) : ℝ) * log (↑p)) k
    (decide (k % 2 = 1)) rfl
  simp only [sub_eq_add_neg] at hscos
  rw [hscos]
  congr 1; norm_num

/-! ### Aggregate Bridge -/

set_option maxHeartbeats 800000 in
set_option linter.style.nativeDecide false in
/-- All neg flags in allTerms are correctly set for the corresponding k values. -/
theorem allTerms_neg_correct :
    allTerms.Forall (fun x => x.2.2 = decide (x.2.1 % 2 = 1)) := by native_decide

set_option maxHeartbeats 40000000 in
set_option linter.style.nativeDecide false in
/-- Domain validity holds for all terms (log arguments are positive). -/
theorem allTerms_domain_valid :
    allTerms.Forall (fun x =>
      checkDomainValid1 (mkRotorTermReduced x.1 x.2.1 x.2.2) ⟨0, 0, le_refl _⟩
        { taylorDepth := 30 } = true) := by native_decide

set_option maxHeartbeats 4000000 in
set_option linter.style.nativeDecide false in
/-- The prime list has the same elements as Nat.primesBelow 7920. -/
theorem primeList_toFinset_eq : primeList.toFinset = Nat.primesBelow 7920 := by native_decide

set_option maxHeartbeats 800000 in
set_option linter.style.nativeDecide false in
/-- The primes in allTerms match primeList exactly. -/
theorem allTerms_primes_eq : allTerms.map Prod.fst = primeList := by native_decide

set_option maxHeartbeats 800000 in
set_option linter.style.nativeDecide false in
/-- primeList has no duplicates. -/
theorem primeList_nodup : primeList.Nodup := by native_decide

set_option maxHeartbeats 800000 in
set_option linter.style.nativeDecide false in
/-- All primes in allTerms are positive. -/
theorem allTerms_pos : allTerms.Forall (fun x => 0 < x.1) := by native_decide

/-! ### Aggregate Bridge Infrastructure -/

/-- Pointwise ≤ implies foldl ≤ (with possibly different starting accumulators). -/
private lemma foldl_add_le {l : List α} {f g : α → ℝ} {a₁ a₂ : ℝ}
    (ha : a₁ ≤ a₂) (h : ∀ x ∈ l, f x ≤ g x) :
    l.foldl (fun acc x => acc + f x) a₁ ≤ l.foldl (fun acc x => acc + g x) a₂ := by
  induction l generalizing a₁ a₂ with
  | nil => exact ha
  | cons x xs ih =>
    simp only [List.foldl_cons]
    exact ih (by linarith [h x (by simp)])
      (fun y hy => h y (by simp [hy]))

/-- Foldl over tuples projecting first component equals foldl over the projected list. -/
private lemma foldl_proj_eq {l : List (ℕ × ℤ × Bool)} {f : ℕ → ℝ} {a : ℝ} :
    l.foldl (fun (acc : ℝ) (x : ℕ × ℤ × Bool) => acc + f x.1) a =
    (l.map Prod.fst).foldl (fun (acc : ℝ) x => acc + f x) a := by
  induction l generalizing a with
  | nil => rfl
  | cons x xs ih => simp only [List.foldl_cons, List.map_cons]; exact ih

/-- ℚ→ℝ cast commutes with foldl over addition (generalized). -/
private lemma foldl_add_cast {l : List α} {f : α → ℚ} {a : ℚ} :
    l.foldl (fun (acc : ℝ) (x : α) => acc + ↑(f x)) (↑a : ℝ) =
    ↑(l.foldl (fun (acc : ℚ) (x : α) => acc + f x) a) := by
  induction l generalizing a with
  | nil => rfl
  | cons x xs ih =>
    simp only [List.foldl_cons]
    rw [show (↑a : ℝ) + ↑(f x) = (↑(a + f x) : ℝ) from by push_cast; ring]
    exact ih

/-! ### Final Bridge Theorem -/

set_option maxHeartbeats 800000 in
/-- The rotor trace bound for primeList, connecting fullCheck to CliffordRH.rotorTrace. -/
theorem rotorTrace_primeList_lt :
    CliffordRH.rotorTrace (1 / 2) 14.134725 primeList < -5 := by
  unfold CliffordRH.rotorTrace
  rw [t_eq]
  -- Relate primeList.foldl to allTerms.foldl via allTerms_primes_eq
  rw [show primeList = allTerms.map Prod.fst from allTerms_primes_eq.symm]
  rw [← foldl_proj_eq]
  -- Each actual term ≤ the interval .hi (upper bound)
  -- Note: after unfolding rotorTrace, exponent is -(1/2); mkTermReduced_eval_eq uses (-1)/2
  have h_le : allTerms.foldl (fun (acc : ℝ) (x : ℕ × ℤ × Bool) =>
      acc + Real.log (x.1 : ℝ) * (x.1 : ℝ) ^ (-(1 / 2 : ℝ)) *
        Real.cos (565389 / 40000 * Real.log (x.1 : ℝ))) 0 ≤
    allTerms.foldl (fun (acc : ℝ) (x : ℕ × ℤ × Bool) =>
      acc + ↑(termIntervalReduced x.1 x.2.1 x.2.2 { taylorDepth := 30 }).hi) 0 := by
    apply foldl_add_le (le_refl _)
    intro ⟨p, k, neg⟩ hx
    have h_neg := (List.forall_iff_forall_mem.mp allTerms_neg_correct) _ hx
    have h_dom := (List.forall_iff_forall_mem.mp allTerms_domain_valid) _ hx
    have h_pos := (List.forall_iff_forall_mem.mp allTerms_pos) _ hx
    have hp : 0 < (p : ℝ) := Nat.cast_pos.mpr h_pos
    calc Real.log (p : ℝ) * (p : ℝ) ^ (-(1 / 2 : ℝ)) *
          Real.cos (565389 / 40000 * Real.log (p : ℝ))
        = Real.log (p : ℝ) * (p : ℝ) ^ ((-1 : ℝ) / 2) *
          Real.cos (565389 / 40000 * Real.log (p : ℝ)) := by
          congr 2; congr 1; ring
      _ = Expr.eval (fun _ => (0 : ℝ)) (mkRotorTermReduced p k neg) :=
          (mkTermReduced_eval_eq p hp k neg h_neg).symm
      _ ≤ ↑(termIntervalReduced p k neg { taylorDepth := 30 }).hi :=
          termReduced_le_hi p k neg _ (checkDomainValid1_correct _ _ _ h_dom)
  -- Cast ℚ foldl to ℝ and use fullCheck bound
  have h_cast : allTerms.foldl (fun (acc : ℝ) (x : ℕ × ℤ × Bool) =>
      acc + ↑(termIntervalReduced x.1 x.2.1 x.2.2 { taylorDepth := 30 }).hi) 0 =
    ↑(allTerms.foldl (fun (acc : ℚ) (x : ℕ × ℤ × Bool) =>
      acc + (termIntervalReduced x.1 x.2.1 x.2.2 { taylorDepth := 30 }).hi) 0) := by
    rw [show (0 : ℝ) = (↑(0 : ℚ) : ℝ) from by simp]
    exact foldl_add_cast
  have h_bound : (2 : ℚ) * allTerms.foldl (fun (acc : ℚ) (x : ℕ × ℤ × Bool) =>
      acc + (termIntervalReduced x.1 x.2.1 x.2.2 { taylorDepth := 30 }).hi) 0 < -5 := by
    have hfc := fullCheck
    unfold rotorTraceCheckReduced at hfc
    simp only [decide_eq_true_eq] at hfc
    exact hfc
  -- Combine: actual ≤ cast(hiSum) and 2*hiSum < -5
  have h_cast_bound : (2 : ℝ) * ↑(allTerms.foldl (fun (acc : ℚ) (x : ℕ × ℤ × Bool) =>
      acc + (termIntervalReduced x.1 x.2.1 x.2.2 { taylorDepth := 30 }).hi) 0) < -5 := by
    exact_mod_cast h_bound
  linarith [h_le, h_cast, h_cast_bound]

/-! ### Permutation Bridge -/

/-- primeList is a permutation of (Nat.primesBelow 7920).toList. -/
private lemma primeList_perm_primesBelow :
    primeList.Perm (Nat.primesBelow 7920).toList :=
  List.perm_of_nodup_nodup_toFinset_eq primeList_nodup (Finset.nodup_toList _)
    (primeList_toFinset_eq.trans (Finset.toList_toFinset _).symm)

/-- rotorTrace is permutation-invariant (foldl over commutative addition). -/
private lemma rotorTrace_perm_eq {l₁ l₂ : List ℕ} (h : l₁.Perm l₂) (σ t : ℝ) :
    CliffordRH.rotorTrace σ t l₁ = CliffordRH.rotorTrace σ t l₂ := by
  unfold CliffordRH.rotorTrace
  congr 1
  have : RightCommutative (fun (acc : ℝ) (p : ℕ) =>
      acc + Real.log ↑p * (↑p) ^ (-σ) * Real.cos (t * Real.log ↑p)) :=
    ⟨fun a _ _ => by ring⟩
  exact h.foldl_eq 0

/-! ### The Final Theorem -/

/-- **Main result**: The rotor trace at the first zeta zero is less than -5.
    This eliminates `rotorTrace_first1000_lt_bound_axiom` from NumericalAxioms.lean. -/
theorem rotorTrace_primesBelow_lt :
    CliffordRH.rotorTrace (1 / 2) 14.134725 (Nat.primesBelow 7920).toList < -5 := by
  rw [← rotorTrace_perm_eq primeList_perm_primesBelow]
  exact rotorTrace_primeList_lt

end

end RotorTraceComputation
